services:
  firebird:
    image: jacobalberty/firebird:2.5-sc
    container_name: firebird-db
    environment:
      FIREBIRD_DATABASE: testdb.fdb
      FIREBIRD_USER: SYSDBA
      FIREBIRD_PASSWORD: masterkey
      ISC_PASSWORD: masterkey
    ports:
      - "3050:3050"
    volumes:
      - firebird_data:/firebird/data
    restart: unless-stopped

volumes:
  firebird_data: